### ISSUE TITLE
java.lang.ClassCastException: class chronosacaria.mcdar.entities.GolemKitGolemEntity cannot be cast to class net.minecraft.class_1657 (chronosacaria.mcdar.entities.GolemKitGolemEntity and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc)

### ISSUE THREAD

**Issue by TheButterbrotMan** [chronosacaria/MCDungonesArtifacts#10] opened 2022-03-07 17:08 UTC
https://bytebin.lucko.me/Vqsn4yuTMq

**Comment by chronosacaria** [comment] 2022-03-07 22:34
The issue you are experiencing is not caused by MCDAR but is caused by MCDW. It was fixed in the latest version. Please update your version of MCDW.

**Closed as completed by chronosacaria** 2022-03-07 22:34 UTC
